#ifndef H_CRAWLER_PROTOCOL
#define H_CRAWLER_PROTOCOL

#define CMD_SET_POWER 1
#define CMD_STOP 2
#define CMD_SET_STEERING_ANGLE 3
#define CMD_RST_ACTUATORS 4

#define DATA_CMD_ECHO 1
#define DATA_SENSORS 2

#endif