#ifndef __SEARCH_FRAME_PARAMS_H
#define __SEARCH_FRAME_PARAMS_H
#include "../include/cuda_basic.h"

__device__ const float TRAVERSABILITY_ANGLES[] = {
    ANGLE_HEADING_MINUS_67_5,
    ANGLE_HEADING_MINUS_45,
    ANGLE_HEADING_MINUS_22_5,
    ANGLE_HEADING_0,
    ANGLE_HEADING_22_5,
    ANGLE_HEADING_45,
    ANGLE_HEADING_67_5,
    ANGLE_HEADING_90,
};

const float H_TRAVERSABILITY_ANGLES[] = {
    ANGLE_HEADING_MINUS_67_5,
    ANGLE_HEADING_MINUS_45,
    ANGLE_HEADING_MINUS_22_5,
    ANGLE_HEADING_0,
    ANGLE_HEADING_22_5,
    ANGLE_HEADING_45,
    ANGLE_HEADING_67_5,
    ANGLE_HEADING_90,
};

__device__ const int TRAVERSABILITY_BITS[] = {
    BIT_HEADING_MINUS_67_5,
    BIT_HEADING_MINUS_45,
    BIT_HEADING_MINUS_22_5,
    BIT_HEADING_0,
    BIT_HEADING_22_5,
    BIT_HEADING_45,
    BIT_HEADING_67_5,
    BIT_HEADING_90};

const int H_TRAVERSABILITY_BITS[] = {
    BIT_HEADING_MINUS_67_5,
    BIT_HEADING_MINUS_45,
    BIT_HEADING_MINUS_22_5,
    BIT_HEADING_0,
    BIT_HEADING_22_5,
    BIT_HEADING_45,
    BIT_HEADING_67_5,
    BIT_HEADING_90};

#define EIGHT_OVER_PI 20.371832716

#endif