#pragma once

#ifndef __SEARCH_PARAMS_DRIVELESS_H
#define __SEARCH_PARAMS_DRIVELESS_H

#define FRAME_PARAM_WIDTH 0
#define FRAME_PARAM_HEIGHT 1
#define FRAME_PARAM_MIN_DIST_X 2
#define FRAME_PARAM_MIN_DIST_Z 3
#define FRAME_PARAM_LOWER_BOUND_X 4
#define FRAME_PARAM_LOWER_BOUND_Z 5
#define FRAME_PARAM_UPPER_BOUND_X 6
#define FRAME_PARAM_UPPER_BOUND_Z 7
#define FRAME_PARAM_CENTER_X 8
#define FRAME_PARAM_CENTER_Z 9
#define FRAME_DENSITY_WIDTH 10
#define FRAME_DENSITY_HEIGHT 11
#define FRAME_DENSITY_SIZE 12

#define PHYSICAL_PARAMS_RATE_W 0
#define PHYSICAL_PARAMS_RATE_H 1
#define PHYSICAL_PARAMS_INV_RATE_W 2
#define PHYSICAL_PARAMS_INV_RATE_H 3
#define PHYSICAL_PARAMS_MAX_STEERING_RAD 4
#define PHYSICAL_PARAMS_MAX_STEERING_DEG 5
#define PHYSICAL_PARAMS_LR 6
#endif

