#pragma once

#ifndef __SEARCH_PARAMS_DRIVELESS_H
#define __SEARCH_PARAMS_DRIVELESS_H

#define PREPROCESS_COLLISION_NONE 0
#define PREPROCESS_COLLISION_DIST 1
#define PREPROCESS_COLLISION_VECTOR 2


#define FRAME_PARAM_WIDTH 0
#define FRAME_PARAM_HEIGHT 1
#define FRAME_PARAM_MIN_DIST_X 2
#define FRAME_PARAM_MIN_DIST_Z 3
#define FRAME_PARAM_LOWER_BOUND_X 4
#define FRAME_PARAM_LOWER_BOUND_Z 5
#define FRAME_PARAM_UPPER_BOUND_X 6
#define FRAME_PARAM_UPPER_BOUND_Z 7
#define FRAME_PARAM_CENTER_X 8
#define FRAME_PARAM_CENTER_Z 9
#define FRAME_PREPROCESS_COLLISION_TYPE 10
#define FRAME_PREPROCESS_DIST_TO_GOAL_ENABLED 11
#define FRAME_SEARCH_ZONE_DIM_WIDTH 12
#define FRAME_SEARCH_ZONE_DIM_HEIGHT 13
#define FRAME_SEARCH_ZONE_GRID_WIDTH 14
#define FRAME_SEARCH_ZONE_GRID_HEIGHT 15
// TODO: this code here is a legacy in FastRRT and it is used to position the SZ in it. 
// It must be replaced by the positioning functions later.
#define FRAME_DENSITY_WIDTH 16
#define FRAME_DENSITY_HEIGHT 17
#define FRAME_DENSITY_SIZE 18


#define PHYSICAL_PARAM_RATE_W 0
#define PHYSICAL_PARAM_RATE_H 1
#define PHYSICAL_PARAM_INV_RATE_W 2
#define PHYSICAL_PARAM_INV_RATE_H 3
#define PHYSICAL_PARAM_MAX_STEERING_RAD 4
#define PHYSICAL_PARAM_MAX_STEERING_DEG 5
#define PHYSICAL_PARAM_WHEELBASE 6
#define PHYSICAL_PARAM_MAX_CURVATURE 7
#endif

